# Generated by Django 5.2.12 on 2026-04-05 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BildirishnomaSozlamasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('tavsif', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('rang', models.CharField(default='#fff3e0', max_length=20)),
                ('icon_rang', models.CharField(default='#f0a500', max_length=20)),
                ('yoqilgan', models.BooleanField(default=True)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bildirishnoma sozlamasi',
                'verbose_name_plural': 'Bildirishnoma sozlamalari',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='DarajaSozlamasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('kerakli_ball', models.PositiveIntegerField(default=1000)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daraja',
                'verbose_name_plural': 'Darajalar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='HaftalikFaoliyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kun', models.CharField(max_length=10)),
                ('soat', models.FloatField(default=0)),
                ('foiz', models.PositiveIntegerField(default=0)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Haftalik faoliyat',
                'verbose_name_plural': 'Haftalik faoliyatlar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='KuchsizSoha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('foiz', models.PositiveIntegerField(default=0)),
                ('rang', models.CharField(default='#ff7043', max_length=20)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kuchsiz soha',
                'verbose_name_plural': 'Kuchsiz sohalar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='KunlikSovrin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kun', models.CharField(max_length=10)),
                ('icon', models.CharField(max_length=50)),
                ('ball', models.PositiveIntegerField(default=10)),
                ('olingan', models.BooleanField(default=False)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kunlik sovrin',
                'verbose_name_plural': 'Kunlik sovrinlar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='Mavzu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.CharField(max_length=10)),
                ('nomi', models.CharField(max_length=200)),
                ('tavsif', models.TextField()),
                ('rang', models.CharField(default='#e8f5e9', max_length=20)),
                ('icon', models.CharField(max_length=50)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=50)),
                ('rang', models.CharField(default='#e8f5e9', max_length=20)),
                ('ball', models.PositiveIntegerField(default=0)),
                ('holat', models.CharField(max_length=50)),
                ('progress_rang', models.CharField(default='#4caf50', max_length=20)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='Musobaqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('tavsif', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('rang', models.CharField(default='#e8f5e9', max_length=20)),
                ('qatnashchilar', models.PositiveIntegerField(default=0)),
                ('daraja', models.CharField(choices=[('Oson', 'Oson'), ("O'rta", "O'rta"), ('Qiyin', 'Qiyin')], default="O'rta", max_length=20)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Musobaqa',
                'verbose_name_plural': 'Musobaqalar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='OquvSozlama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('tavsif', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('rang', models.CharField(default='#e8f5e9', max_length=20)),
                ('icon_rang', models.CharField(default='#4caf50', max_length=20)),
                ('turi', models.CharField(choices=[('toggle', 'Toggle'), ('select', 'Select')], default='toggle', max_length=20)),
                ('qiymat_bool', models.BooleanField(default=False, help_text='Toggle turi uchun')),
                ('qiymat_text', models.CharField(blank=True, help_text='Select turi uchun', max_length=100)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "O'quv sozlamasi",
                'verbose_name_plural': "O'quv sozlamalari",
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='OtaOnaMaslahat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=50)),
                ('rang', models.CharField(default='#e8f5e9', max_length=20)),
                ('tavsif', models.TextField()),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ota-ona maslahati',
                'verbose_name_plural': 'Ota-ona maslahatlari',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('yosh', models.PositiveIntegerField(default=12)),
                ('sinf', models.CharField(max_length=50)),
                ('maktab', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='ReytingOyinchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200)),
                ('ball', models.PositiveIntegerField(default=0)),
                ('medal', models.CharField(blank=True, max_length=50)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Reyting oyinchisi',
                'verbose_name_plural': 'Reyting oyinchilari',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('rang', models.CharField(max_length=20)),
                ('preview_rang', models.CharField(max_length=20)),
                ('tanlangan', models.BooleanField(default=False)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temalar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='Topshiriq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('tavsif', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('rang', models.CharField(default='#e8f5e9', max_length=20)),
                ('savollar', models.PositiveIntegerField(default=0)),
                ('foiz', models.PositiveIntegerField(default=0)),
                ('progress_rang', models.CharField(blank=True, max_length=20)),
                ('btn_rang', models.CharField(blank=True, max_length=20)),
                ('turi', models.CharField(choices=[('kichik', 'Kichik topshiriq'), ('pastki', 'Pastki topshiriq')], default='kichik', max_length=20)),
                ('rasm_url', models.URLField(blank=True)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Topshiriq',
                'verbose_name_plural': 'Topshiriqlar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='UmumiyStatistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umumiy_ball', models.PositiveIntegerField(default=82)),
                ('bajarilgan', models.PositiveIntegerField(default=24)),
                ('jarayonda', models.PositiveIntegerField(default=12)),
                ('umumiy_soat', models.PositiveIntegerField(default=47)),
                ('ketma_ket_kun', models.PositiveIntegerField(default=7)),
                ('ortacha_ball_foiz', models.PositiveIntegerField(default=89)),
                ('yulduzcha', models.PositiveIntegerField(default=150)),
            ],
            options={
                'verbose_name': 'Umumiy statistika',
                'verbose_name_plural': 'Umumiy statistika',
            },
        ),
        migrations.CreateModel(
            name='XavfsizlikSozlamasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('tavsif', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('rang', models.CharField(default='#fff3e0', max_length=20)),
                ('icon_rang', models.CharField(default='#f0a500', max_length=20)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Xavfsizlik sozlamasi',
                'verbose_name_plural': 'Xavfsizlik sozlamalari',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='Yutuq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=50)),
                ('rang', models.CharField(default='#fff3e0', max_length=20)),
                ('tavsif', models.TextField()),
                ('ball', models.PositiveIntegerField(default=0)),
                ('sana', models.DateField(blank=True, null=True)),
                ('olingan', models.BooleanField(default=False)),
                ('foiz', models.PositiveIntegerField(default=0, help_text='Faqat olinmagan yutuqlar uchun progress foizi')),
                ('progress_rang', models.CharField(blank=True, max_length=20)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Yutuq',
                'verbose_name_plural': 'Yutuqlar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='Dars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.CharField(max_length=10)),
                ('nomi', models.CharField(max_length=200)),
                ('tavsif', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('rang', models.CharField(default='#e8f5e9', max_length=20)),
                ('davomiylik', models.CharField(max_length=50)),
                ('holat', models.CharField(choices=[('tugallangan', 'Tugallangan'), ('jarayonda', 'Jarayonda'), ('qulflangan', 'Qulflangan')], default='qulflangan', max_length=20)),
                ('tartib', models.PositiveIntegerField(default=0)),
                ('kategoriya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='darslar', to='apps.kategoriya')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['tartib'],
            },
        ),
    ]
