# Generated by Django 5.2.12 on 2026-04-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongiFaoliyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('rang', models.CharField(default='#4caf50', max_length=20)),
                ('sahifa', models.CharField(choices=[('bosh_sahifa', 'Bosh sahifa'), ('darslar', 'Darslar'), ('topshiriqlar', 'Topshiriqlar'), ('statistika', 'Statistika'), ('yutuqlar', 'Yutuqlar'), ('sozlamalar', 'Sozlamalar')], default='bosh_sahifa', help_text="Qaysi sahifada ko'rinadi", max_length=50)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "So'nggi faoliyat",
                'verbose_name_plural': "So'nggi faoliyatlar",
                'ordering': ['tartib'],
            },
        ),
    ]
