# Generated by Django 5.2.12 on 2026-04-05 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_songifaoliyat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profillar'},
        ),
        migrations.AddField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profil',
            name='maktab',
            field=models.CharField(default="Umumta'lim maktabi", max_length=200),
        ),
        migrations.AlterField(
            model_name='profil',
            name='sinf',
            field=models.CharField(default='6-sinf', max_length=50),
        ),
    ]
