# Generated by Django 5.2.12 on 2026-04-05 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_profil_options_profil_user_alter_profil_maktab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dars',
            name='mazmun',
            field=models.TextField(blank=True, help_text='Dars matni (HTML yoki oddiy matn)'),
        ),
        migrations.CreateModel(
            name='Savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol_matni', models.TextField()),
                ('variant_a', models.CharField(max_length=200)),
                ('variant_b', models.CharField(max_length=200)),
                ('variant_c', models.CharField(max_length=200)),
                ('variant_d', models.CharField(max_length=200)),
                ('togri_javob', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('izoh', models.TextField(blank=True, help_text='Javob izohi')),
                ('tartib', models.PositiveIntegerField(default=0)),
                ('topshiriq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savollar_list', to='apps.topshiriq')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['tartib'],
            },
        ),
    ]
