# Generated by Django 5.2.12 on 2026-04-05 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_dars_mazmun_savol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestNatija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('togri_soni', models.PositiveIntegerField(default=0)),
                ('umumiy_soni', models.PositiveIntegerField(default=0)),
                ('foiz', models.PositiveIntegerField(default=0)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('batafsil', models.JSONField(blank=True, default=list, help_text='Har bir savol natijalari')),
                ('topshiriq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to='apps.topshiriq')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_natijalari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['-sana'],
            },
        ),
    ]
