# Generated by Django 5.2.12 on 2026-04-06 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_testnatija'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusobaqaNatija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('togri_soni', models.PositiveIntegerField(default=0)),
                ('umumiy_soni', models.PositiveIntegerField(default=0)),
                ('foiz', models.PositiveIntegerField(default=0)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('batafsil', models.JSONField(blank=True, default=list)),
                ('musobaqa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to='apps.musobaqa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musobaqa_natijalari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Musobaqa natijasi',
                'verbose_name_plural': 'Musobaqa natijalari',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='MusobaqaSavol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol_matni', models.TextField()),
                ('variant_a', models.CharField(max_length=200)),
                ('variant_b', models.CharField(max_length=200)),
                ('variant_c', models.CharField(max_length=200)),
                ('variant_d', models.CharField(max_length=200)),
                ('togri_javob', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('izoh', models.TextField(blank=True, help_text='Javob izohi')),
                ('tartib', models.PositiveIntegerField(default=0)),
                ('musobaqa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savollar', to='apps.musobaqa')),
            ],
            options={
                'verbose_name': 'Musobaqa savoli',
                'verbose_name_plural': 'Musobaqa savollari',
                'ordering': ['tartib'],
            },
        ),
    ]
