# Generated by Django 5.2.12 on 2026-04-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_musobaqanatija_musobaqasavol'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='rol',
            field=models.CharField(choices=[('oquvchi', "O'quvchi"), ('oqituvchi', "O'qituvchi")], default='oquvchi', max_length=20),
        ),
    ]
