# Generated by Django 5.2.12 on 2026-04-11 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_profil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='topshiriq',
            name='dars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topshiriqlar', to='apps.dars'),
        ),
    ]
