# Generated by Django 5.2.12 on 2026-05-07 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_topshiriq_dars'),
    ]

    operations = [
        migrations.AddField(
            model_name='topshiriq',
            name='mavzu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topshiriqlar', to='apps.mavzu'),
        ),
    ]
