# Generated by Django 5.2.12 on 2026-06-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_topshiriq_mavzu'),
    ]

    operations = [
        migrations.AddField(
            model_name='dars',
            name='amaliy_uslubiy',
            field=models.TextField(blank=True, help_text="Amaliy-uslubiy ko'rsatma (HTML)"),
        ),
        migrations.AddField(
            model_name='dars',
            name='nazariy',
            field=models.TextField(blank=True, help_text='Nazariy qism (HTML)'),
        ),
        migrations.AddField(
            model_name='dars',
            name='taqdimot',
            field=models.TextField(blank=True, help_text='Taqdimot matni / slaydlar (HTML)'),
        ),
        migrations.AddField(
            model_name='dars',
            name='taqdimot_fayl',
            field=models.FileField(blank=True, help_text='Taqdimot fayli (.pptx)', null=True, upload_to='gis/taqdimotlar/'),
        ),
        migrations.AddField(
            model_name='dars',
            name='topshiriq_matni',
            field=models.TextField(blank=True, help_text='Topshiriq matni (HTML)'),
        ),
    ]
