# Generated by Django 5.2.12 on 2026-06-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_dars_amaliy_uslubiy_dars_nazariy_dars_taqdimot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adabiyot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300)),
                ('tavsif', models.TextField(blank=True)),
                ('fayl', models.FileField(help_text='PDF yoki boshqa hujjat', upload_to='adabiyotlar/')),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Adabiyot',
                'verbose_name_plural': 'Adabiyotlar',
                'ordering': ['tartib'],
            },
        ),
    ]
