# Generated by Django 5.2.12 on 2026-06-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_adabiyot'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300)),
                ('tavsif', models.TextField(blank=True)),
                ('youtube_id', models.CharField(help_text='YouTube video ID (masalan: NHolzMgaqwE)', max_length=40)),
                ('davomiylik', models.CharField(blank=True, max_length=50)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Video dars',
                'verbose_name_plural': 'Video darslar',
                'ordering': ['tartib'],
            },
        ),
    ]
